language: node_js
node_js:
    - "7"

install: true

before_script:
  - "npm install -g jshint jscs"

script:
  - "jshint src/app.js src/js/*.js src/js/win/*.js; jscs src/app.js src/js/*.js src/js/win/*.js"
